version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: musica_DB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # ESTO ES LO NUEVO: Revisa cada 10 seg si MySQL ya responde consultas
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  musicadb-app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      mysqldb:
        condition: service_healthy # Espera obligatoriamente al healthcheck
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/musica_DB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data: